name: Auto Bump

on:
  workflow_dispatch:
    
  schedule:
    - cron: '0 0 * * *'
  
concurrency:
  group: "bump"
  cancel-in-progress: true

jobs:
  check-version:
    name: Check latest version

    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        
      - name: Install packages
        run: npm ci
        working-directory: ./update_checker

      - name: Run checker
        run: node app
        working-directory: ./update_checker

      - name: Echo test
        run: echo $?