name: Auto Bump

on:
  workflow_dispatch:
    
  schedule:
    - cron: '0 0 * * *'
  
concurrency:
  group: "bump"
  cancel-in-progress: true

jobs:
  check_version:
    name: Check latest version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        
      - name: Install packages
        working-directory: ./update_checker
        run: npm ci
        
      - name: Run checker
        id: checker
        working-directory: ./update_checker
        continue-on-error: true
        run: node app

      - name: Run bump
        if: steps.checker.outcome == 'success'
        run: echo "run the thing"

      - name: Result
        if: steps.checker.outcome != 'success'
        run: echo "No update"

  trigger_bump:
    name: Trigger bump
    needs: check_version
    runs-on: ubuntu-latest
    if: needs.check_version.result == success
    steps:
      - run: echo "Run the thing"

  no_update:
    name: No update
    needs: check_version
    runs-on: ubuntu-latest
    if: needs.check_version.result != success
    steps:
      - run: echo "Nothing to update"