name: Bump save editor data

on:
  workflow_dispatch:
  
concurrency:
  group: "bump"
  cancel-in-progress: true
  
jobs:
  create_pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: test_msg
          title: test_title
          body: test_body
          branch: test_branch
    
    
